#!/bin/bash -e

. config.conf

BASEDIR=$(pwd)

if test “${DOWNLOAD_NASM}” = “1”;
then
    echo "Downloading NASM ..."
    cd "${BASEDIR}"
    curl -L -# -o nasm.zip ${NASM_DOWNLOAD_URL} 2>&1
    rm -rf "$NASM_DIR_NAME"
    echo "NASM downloaded!"
    echo "Extracting NASM ..."
    unzip -qo nasm.zip && rm -rf nasm.zip

fi

if test “${DOWNLOAD_PJSIP}” = “1”;
then
    echo "Downloading PJSIP ..."
    cd "${BASEDIR}"
    curl -L -# -o pjsip.tar.bz2 ${PJSIP_DOWNLOAD_URL} 2>&1
    rm -rf "$PJSIP_DIR_NAME"
    echo "PJSIP downloaded!"
    echo "Extracting PJSIP ..."
    tar xjf pjsip.tar.bz2 && rm -rf pjsip.tar.bz2

    if test "${PJSIP_DIR_NAME}" = "pjproject-2.6";
    then
        echo "Apply patch to support G.729 codec without Intel IPP codec library ..."
        cd g729_patch
        ./install.sh
        cd ..
    fi
fi

if test “${DOWNLOAD_OPENSSL}” = “1”;
then
    echo "Downloading OpenSSL ..."
    cd "${BASEDIR}"
    curl -L -# -o openssl.tar.gz $OPENSSL_DOWNLOAD_URL 2>&1
    rm -rf "$OPENSSL_DIR_NAME"
    echo "OpenSSL downloaded!"
    echo "Extracting OpenSSL ..."
    tar xzf openssl.tar.gz && rm -rf openssl.tar.gz
    cd ${BASEDIR}
    ./openssl-build-target-archs
fi

if test “${DOWNLOAD_OPENH264}” = “1”;
then
    echo "Downloading OpenH264 ..."
    cd "${BASEDIR}"
    curl -L -# -o openh264.tar.gz $OPENH264_DOWNLOAD_URL 2>&1
    rm -rf "${OPENH264_DIR_NAME}"
    echo "OpenH264 downloaded!"
    echo "Extracting OpenH264 ..."
    tar xzf openh264.tar.gz && rm -rf openh264.tar.gz
    cd ${BASEDIR}
    ./openh264-build-target-archs || true
fi

echo "The build system is ready! Execute: ./build to build PJSIP"
